### ISSUE TITLE
Rewards being consumed as fee

### ISSUE THREAD

**Issue by nkoele413** [atomiclabs/ledger-kmd-reward-claim#10]
The last two times I have claimed rewards the transaction has converted the reward amount to the fee amount.

**Comment by lukechilds** [comment]
If you see a negative fee on a block explorer site this is a bug with how the block explorers show transactions. If you check the input amount and output amount you should see they are correct.

Can you send me a TXID so I can check for you?

**Comment by nkoele413** [comment]
Sure thing

8/14
send
40c6edc12ef9633d86e23e4082f3d47cc256c5ba7d341f424e100eac228d84e1
recieve
40c6edc12ef9633d86e23e4082f3d47cc256c5ba7d341f424e100eac228d84e1

7/30
send
ec69dd379d1c6006694bf7f337d7faf55d852b4731871150bacb8df62e25552d
recieve
3bce4e86b2f4964ef931d884eb2699c6da721aeb13dabe5980a61f47c236fccb

**Comment by lukechilds** [comment]
There are three claim transactions there. Also there is no separate send and receive transactions, just one transaction that sends back to yourself.

Of those three TXIDs you sent, all are correctly claimed. The negative fee is a bug with the block explorers but if you add up the inputs and outputs, you can see the output amount is higher.

The negative fee shown is the inverted amount of rewards claimed.

e.g in this transaction: https://www.kmdexplorer.io/tx/40c6edc12ef9633d86e23e4082f3d47cc256c5ba7d341f424e100eac228d84e1

Inputs:
188.05046209 KMD
3355.35840339 KMD

Total: 3543.40886548 KMD

Output:
3550.51893039 KMD

Rewards claimed: 7.11006491

Same goes for the other two transactions:
https://www.kmdexplorer.io/tx/ec69dd379d1c6006694bf7f337d7faf55d852b4731871150bacb8df62e25552d
https://www.kmdexplorer.io/tx/3bce4e86b2f4964ef931d884eb2699c6da721aeb13dabe5980a61f47c236fccb

**Comment by nkoele413** [comment]
Ah, I gotcha. Thank you for looking into this and taking the time to
explain it.
