### ISSUE TITLE
User feedback on the service fee

### ISSUE THREAD

**Issue by lukechilds** [atomiclabs/ledger-kmd-reward-claim#2]
You can read about why there is a 5% fee [here](https://github.com/atomiclabs/ledger-kmd-reward-claim#why-do-i-have-to-pay-a-5-fee).

Feel free to give us feedback and let us know how you feel about these fees.

You can click to vote on the poll below:

[![](https://api.gh-polls.com/poll/01D1TCCTYCYZ2QB2553X1MX9NY/I%20think%20the%205%25%20fee%20is%20fair)](https://api.gh-polls.com/poll/01D1TCCTYCYZ2QB2553X1MX9NY/I%20think%20the%205%25%20fee%20is%20fair/vote)
[![](https://api.gh-polls.com/poll/01D1TCCTYCYZ2QB2553X1MX9NY/I%20think%20the%205%25%20fee%20is%20too%20high)](https://api.gh-polls.com/poll/01D1TCCTYCYZ2QB2553X1MX9NY/I%20think%20the%205%25%20fee%20is%20too%20high/vote)
[![](https://api.gh-polls.com/poll/01D1TCCTYCYZ2QB2553X1MX9NY/I%20think%20the%205%25%20fee%20is%20too%20low)](https://api.gh-polls.com/poll/01D1TCCTYCYZ2QB2553X1MX9NY/I%20think%20the%205%25%20fee%20is%20too%20low/vote)

**Comment by JSterling8** [comment]
I can vote on this multiple times.

**Comment by JSterling8** [comment]
That is, I was able to vote once for each of the 3 options.

**Comment by lukechilds** [comment]
@jsterling8 I think it's limited by IP. It's only supposed to give a rough overview.

https://github.com/apex/gh-polls

Wisdom of the crowd.

**Comment by lukechilds** [comment]
Closing this issue as we've decided to make the service free https://github.com/atomiclabs/ledger-kmd-reward-claim/commit/5da58c411fd1267b6a2930c143da64bc2f6153d1
