### ISSUE TITLE
Ledger device: Internal error, please report (0x6f02)

### ISSUE THREAD

**Issue by dharmicwarrior** [atomiclabs/ledger-kmd-reward-claim#5]
Fully updated firmware + Komodo app on Ledger Blue

follow all steps fine until: Approve the transaction on your device after carefully checking the values and addresses match those shown above.

Which flashes red and gives the following error: Ledger device: Internal error, please report (0x6f02)

Unsure what to do from here, please advise.

**Comment by lukechilds** [comment]
Sorry, I don't have a Ledger Blue device to test on.

Can you transact normally with Ledger Live without the errors?

**Comment by dharmicwarrior** [comment]
I just tried, no I cannot. I get the exact same error message.

Any recommendations on how to resolve? I’m guessing it’s my ledger that’s at fault here.

I do not have the Komodo app downloaded in live (it didn’t give the option) only in the original ledger wallet app.

**Comment by lukechilds** [comment]
>I’m guessing it’s my ledger that’s at fault here.

Yep, sounds like it.

>I do not have the Komodo app downloaded in live (it didn’t give the option) only in the original ledger wallet app.

Do you mean you are using the old Chrome extension wallet/manager apps?

I think you need to use Ledger Live to get the latest app/firmware for your device. I don't think the Chrome apps are supported any more.

**Comment by dharmicwarrior** [comment]
Yes correct. The crome extensions.

I’ve managed to update my firmware and get ledger live loaded, however when looking in the manager I have the most up to date firmware, but there is no option for Komodo within the App Catalog.

**Comment by lukechilds** [comment]
Sorry, I think you need to contact Ledger support, the issue definitely seems to be with the Ledger and not this app.

For reference the latest version of the KMD app is 1.3.7 which is required to claim rewards without issue.

I'll close this issue for now, but feel free to re-open in the future if you still have issues claiming with our app after you've resolved the issues with Ledger.
