### ISSUE TITLE
Locktime

### ISSUE THREAD

**Issue by ElvisPresly** [atomiclabs/ledger-kmd-reward-claim#6]
What does Locktime mean?
<img width="114" alt="screen shot 2019-02-19 at 14 04 40 pm" src="https://user-images.githubusercontent.com/18265958/53010601-6995da80-344f-11e9-8e45-e9cc68cfb6dc.png">

Why I have a red badge?

**Comment by lukechilds** [comment]
Locktime needs to be set on a transaction for it to be eligible to accrue interest.

If you have the red cross that means you used a wallet that doesn't support setting locktime so your UTXOs won't accrue interest.

**Comment by ElvisPresly** [comment]
Ledger Live not support locktime?

**Comment by lukechilds** [comment]
No, unfortunately not.

**Comment by ElvisPresly** [comment]
What is alternatives? After all to keep the deposit on Ledger loses sense if still award not charged.

**Comment by lukechilds** [comment]
If you send from Agama/komodod to your Ledger then your UTXOs will still accrue interest.

It's only making additional transactions inside Ledger Live that will not have nLockTime set.

**Comment by lukechilds** [comment]
@ElvisPresly I have submitted a PR to add this functionality to Ledger Live: https://github.com/LedgerHQ/ledger-live-desktop/pull/1825

**Comment by lukechilds** [comment]
Closing this as it's been merged into Ledger Live 1.5.0 🎉
