### ISSUE TITLE
stuck on Scanning Blockchain for Rewards

### ISSUE THREAD

**Issue by Kiruel** [atomiclabs/ledger-kmd-reward-claim#9]
<img width="821" alt="Screenshot 2019-06-09 at 12 01 02" src="https://user-images.githubusercontent.com/8250175/59157651-654d0600-8aae-11e9-922b-db2cec7a89d9.png">

I'm stuck here, I use nano S version firmware 1.5.5

**Comment by lukechilds** [comment]
Are you on the Latest Komodo app (1.3.9)?

And what browser are you using?

**Comment by Kiruel** [comment]
Ok it works now with the new version.
